//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechDashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechDashboard.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Analytics data and charts will be displayed here. 的本地化字符串。
        /// </summary>
        public static string Analytics_Description {
            get {
                return ResourceManager.GetString("Analytics_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analytics Page 的本地化字符串。
        /// </summary>
        public static string Analytics_Title {
            get {
                return ResourceManager.GetString("Analytics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Users 的本地化字符串。
        /// </summary>
        public static string Dashboard_ActiveUsers {
            get {
                return ResourceManager.GetString("Dashboard_ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All systems operational 的本地化字符串。
        /// </summary>
        public static string Dashboard_AllSystemsOK {
            get {
                return ResourceManager.GetString("Dashboard_AllSystemsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Load 的本地化字符串。
        /// </summary>
        public static string Dashboard_CPULoad {
            get {
                return ResourceManager.GetString("Dashboard_CPULoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk I/O 的本地化字符串。
        /// </summary>
        public static string Dashboard_DiskIO {
            get {
                return ResourceManager.GetString("Dashboard_DiskIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Errors (24h) 的本地化字符串。
        /// </summary>
        public static string Dashboard_Errors24h {
            get {
                return ResourceManager.GetString("Dashboard_Errors24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Usage 的本地化字符串。
        /// </summary>
        public static string Dashboard_MemoryUsage {
            get {
                return ResourceManager.GetString("Dashboard_MemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Traffic 的本地化字符串。
        /// </summary>
        public static string Dashboard_NetworkTraffic {
            get {
                return ResourceManager.GetString("Dashboard_NetworkTraffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Performance 的本地化字符串。
        /// </summary>
        public static string Dashboard_Performance {
            get {
                return ResourceManager.GetString("Dashboard_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TechDashboard 的本地化字符串。
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ↑ 12.5% vs last month 的本地化字符串。
        /// </summary>
        public static string Dashboard_VsLastMonth {
            get {
                return ResourceManager.GetString("Dashboard_VsLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("Menu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("Menu_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string Menu_Edit_Redo {
            get {
                return ResourceManager.GetString("Menu_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string Menu_Edit_Undo {
            get {
                return ResourceManager.GetString("Menu_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fullscreen 的本地化字符串。
        /// </summary>
        public static string Menu_View_Fullscreen {
            get {
                return ResourceManager.GetString("Menu_View_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Menu_View_Refresh {
            get {
                return ResourceManager.GetString("Menu_View_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analytics 的本地化字符串。
        /// </summary>
        public static string Nav_Analytics {
            get {
                return ResourceManager.GetString("Nav_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        public static string Nav_Collapse {
            get {
                return ResourceManager.GetString("Nav_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DASHBOARD 的本地化字符串。
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand Navigation 的本地化字符串。
        /// </summary>
        public static string Nav_Expand {
            get {
                return ResourceManager.GetString("Nav_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview 的本地化字符串。
        /// </summary>
        public static string Nav_Overview {
            get {
                return ResourceManager.GetString("Nav_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reports 的本地化字符串。
        /// </summary>
        public static string Nav_Reports {
            get {
                return ResourceManager.GetString("Nav_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generated reports and export options will be displayed here. 的本地化字符串。
        /// </summary>
        public static string Reports_Description {
            get {
                return ResourceManager.GetString("Reports_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reports Page 的本地化字符串。
        /// </summary>
        public static string Reports_Title {
            get {
                return ResourceManager.GetString("Reports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Language 的本地化字符串。
        /// </summary>
        public static string Settings_ChooseLanguage {
            get {
                return ResourceManager.GetString("Settings_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Theme 的本地化字符串。
        /// </summary>
        public static string Settings_ChooseTheme {
            get {
                return ResourceManager.GetString("Settings_ChooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Settings_Lang_Chinese {
            get {
                return ResourceManager.GetString("Settings_Lang_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Settings_Lang_English {
            get {
                return ResourceManager.GetString("Settings_Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        public static string Settings_Lang_Japanese {
            get {
                return ResourceManager.GetString("Settings_Lang_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 한국어 的本地化字符串。
        /// </summary>
        public static string Settings_Lang_Korean {
            get {
                return ResourceManager.GetString("Settings_Lang_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁體中文 的本地化字符串。
        /// </summary>
        public static string Settings_Lang_TraditionalChinese {
            get {
                return ResourceManager.GetString("Settings_Lang_TraditionalChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue Tech 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_BlueTech {
            get {
                return ResourceManager.GetString("Settings_Theme_BlueTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Page: 的本地化字符串。
        /// </summary>
        public static string Status_CurrentPage {
            get {
                return ResourceManager.GetString("Status_CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        public static string Status_Language {
            get {
                return ResourceManager.GetString("Status_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analytics 的本地化字符串。
        /// </summary>
        public static string Status_Page_Analytics {
            get {
                return ResourceManager.GetString("Status_Page_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview 的本地化字符串。
        /// </summary>
        public static string Status_Page_Overview {
            get {
                return ResourceManager.GetString("Status_Page_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reports 的本地化字符串。
        /// </summary>
        public static string Status_Page_Reports {
            get {
                return ResourceManager.GetString("Status_Page_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Status_Page_Settings {
            get {
                return ResourceManager.GetString("Status_Page_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme: 的本地化字符串。
        /// </summary>
        public static string Status_Theme {
            get {
                return ResourceManager.GetString("Status_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue Tech 的本地化字符串。
        /// </summary>
        public static string Status_Theme_BlueTech {
            get {
                return ResourceManager.GetString("Status_Theme_BlueTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Status_Theme_Dark {
            get {
                return ResourceManager.GetString("Status_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Status_Theme_Light {
            get {
                return ResourceManager.GetString("Status_Theme_Light", resourceCulture);
            }
        }
    }
}
